namespace LootLogger.App.Localization;

/// <summary>Interface texts. Item names come from the game data in the matching language.</summary>
internal static class Strings
{
    public static readonly Dictionary<string, string> Portuguese = new()
    {
        // Menu
        ["NavDashboard"] = "Painel",
        ["NavLootLog"] = "Loot Log",
        ["NavChest"] = "Comparar Baú",
        ["NavCombat"] = "Combate",
        ["NavSettings"] = "Configurações",
        ["NavNews"] = "Novidades",
        ["NavHelp"] = "Ajuda",
        ["NavAbout"] = "Sobre",

        // Status
        ["InGame"] = "No jogo",
        ["OutOfGame"] = "Fora do jogo",
        ["ServerAmericas"] = "Américas",
        ["ServerEurope"] = "Europa",
        ["ServerAsia"] = "Ásia",
        ["ServerUnknown"] = "Servidor desconhecido",
        ["WaitingGame"] = "Esperando o jogo… entre no personagem ou troque de mapa",
        ["PartyCount"] = "Party: {0}",
        ["Solo"] = "Sem party",

        // Dashboard
        ["ExportCsv"] = "Exportar CSV",
        ["NewSession"] = "Nova sessão",
        ["TileItems"] = "ITENS CAPTURADOS",
        ["TileLastHour"] = "ÚLTIMA HORA",
        ["TileActive"] = "TEMPO ATIVO",
        ["TileValue"] = "VALOR ESTIMADO",
        ["RecentEvents"] = "EVENTOS RECENTES",
        ["NoEventsYet"] = "Nada capturado ainda. Pegue uma bag no jogo e ela aparece aqui.",
        ["FeedLoot"] = "{0} pegou {1}{2} de {3}",
        ["FeedKill"] = "{0} ({1}) morreu para {2} ({3})",
        ["FeedSessionStarted"] = "Sessão iniciada",
        ["FeedCaptureStarted"] = "Captura iniciada",
        ["FeedCaptureStopped"] = "Captura parada",
        ["FeedGameDetected"] = "Tráfego do jogo detectado",
        ["FeedMapChanged"] = "Mapa: {0}",
        ["NpcapMissingTitle"] = "Falta o Npcap",
        ["NpcapMissingText"] = "O LootLogger usa o Npcap (gratuito) para ler o tráfego do jogo. Instale e abra o programa de novo.",
        ["NpcapDownload"] = "Baixar Npcap",
        ["CaptureError"] = "Não deu para iniciar a captura: {0}",
        ["RecordError"] = "A captura continua, mas não deu para gravar: {0}",
        ["Exported"] = "Exportado: {0}",
        ["NothingToExport"] = "Ainda não há nada para exportar.",
        ["ConfirmNewSession"] = "Começar uma sessão nova? A atual já está salva em {0}.",
        ["Yes"] = "Sim",
        ["No"] = "Não",
        ["Mob"] = "monstro",
        ["Million"] = "mi",
        ["Thousand"] = "mil",

        // Loot log
        ["SearchHint"] = "Buscar jogador ou item…",
        ["AllGuilds"] = "Todas as guilds",
        ["ColTime"] = "HORÁRIO",
        ["ColLootedBy"] = "QUEM PEGOU",
        ["ColItem"] = "ITEM",
        ["ColQty"] = "QTD",
        ["ColLootedFrom"] = "DE QUEM",
        ["ColMap"] = "MAPA",
        ["ColValue"] = "VALOR",
        ["LootSummary"] = "{0} itens · {1} jogadores",

        // Chest
        ["PasteChestLog"] = "Colar log do baú",
        ["OpenFile"] = "Abrir arquivo…",
        ["ClearChest"] = "Limpar",
        ["ChestHowTo"] = "No jogo, abra o baú da guild, vá em Log, clique em Copiar e depois em Colar log do baú aqui. Pode colar várias abas.",
        ["TileSessionLoot"] = "LOOT DA SESSÃO",
        ["TileDeposited"] = "DEPOSITADO",
        ["TileMissing"] = "FALTANDO",
        ["TileMissingValue"] = "VALOR FALTANDO",
        ["ByPlayer"] = "POR JOGADOR",
        ["SortedByMissing"] = "ordenado pelo que falta",
        ["ColPlayer"] = "JOGADOR",
        ["ColLooted"] = "PEGOU",
        ["ColDeposited"] = "DEPOSITOU",
        ["ColMissing"] = "FALTA",
        ["ColMissingItems"] = "ITENS QUE FALTAM",
        ["ColStatus"] = "SITUAÇÃO",
        ["StatusOk"] = "Ok",
        ["StatusPartial"] = "Parcial",
        ["StatusPending"] = "Pendente",
        ["ChestLinesRead"] = "{0} linhas do baú lidas",
        ["ChestNothingRead"] = "Não achei linhas de log do baú no texto copiado.",

        // Combat
        ["OnlyMyGuild"] = "Só minha guild",
        ["TileKills"] = "ABATES",
        ["TileDeaths"] = "MORTES",
        ["ColDied"] = "MORREU",
        ["ColKiller"] = "MATOU",
        ["ColLost"] = "PERDEU",
        ["NothingLost"] = "—",

        // Settings
        ["PartyMode"] = "Modo Party",
        ["PartyModeHelp"] = "Registra só o loot de quem está na sua party.",
        ["Language"] = "Idioma",
        ["LanguageHelp"] = "Muda os textos do programa. Nomes de itens seguem o idioma escolhido.",
        ["Adapter"] = "Placa de rede",
        ["AdapterHelp"] = "Deixe em Automático: funciona com ExitLag e não precisa do Npcap. Escolher uma placa usa o Npcap.",
        ["AdapterAuto"] = "Automático (todas)",
        ["ExportFolder"] = "Pasta dos arquivos exportados",
        ["Change"] = "Trocar…",
        ["OpenFolder"] = "Abrir pasta",
        ["ItemList"] = "Lista de itens",
        ["ItemListHelp"] = "{0} itens carregados. Atualiza sozinha quando o jogo ganha itens novos.",
        ["UpdateNow"] = "Atualizar agora",
        ["ItemListUpdated"] = "Lista de itens atualizada.",
        ["ItemListFailed"] = "Não deu para atualizar a lista de itens agora.",
        ["Advanced"] = "Avançado",
        ["RecordCapture"] = "Gravar captura para diagnóstico",
        ["RecordCaptureHelp"] = "Salva o tráfego do jogo num arquivo .pcap na pasta de dados. Use só se pedirem para ajudar a achar um erro.",
        ["ReplayRecording"] = "Abrir gravação…",
        ["OpenDataFolder"] = "Pasta de dados",

        // About
        ["AboutMadeBy"] = "Feito por Vitor. Só lê o tráfego do jogo; não altera o cliente nem joga por você.",
        ["AboutFanProject"] = "Projeto de fã, sem vínculo com a Sandbox Interactive GmbH. Albion Online é marca da Sandbox Interactive.",
        ["AboutLicense"] = "Código aberto sob a licença GPL-3.0.",
        ["AboutCredits"] = "Usa partes do AlbionOnline-StatisticsAnalysis (Triky313, GPL-3.0), SharpPcap, PacketDotNet, CommunityToolkit.Mvvm, a fonte Geist e a lista de itens do ao-bin-dumps.",
        ["Version"] = "versão {0}",

        // News / help
        ["NewsBody"] = "Primeira versão: captura ao vivo, Loot Log, exportação em CSV no formato que as guilds já usam, Comparar Baú, Combate, Modo Party e português/inglês.",
        ["HelpNoCapture"] = "Não captura nada?",
        ["HelpNoCaptureText"] = "Confira se a placa de rede está em Automático e se o Windows pediu permissão de administrador ao abrir. Depois troque de mapa no jogo.",
        ["HelpExitLag"] = "Uso ExitLag.",
        ["HelpExitLagText"] = "Funciona sem configurar nada: deixe a placa de rede em Automático.",
        ["HelpPlayer"] = "Aparece \"jogador não identificado\".",
        ["HelpPlayerText"] = "O jogo só manda o seu nome ao entrar no personagem ou trocar de mapa. Abra o LootLogger antes de entrar no jogo, ou troque de mapa.",
        ["HelpWarning"] = "O Windows avisou sobre o programa.",
        ["HelpWarningText"] = "Programas novos e sem assinatura recebem esse aviso. Baixe só da página oficial de releases no GitHub e clique em Mais informações > Executar assim mesmo.",
        ["HelpMerge"] = "Como juntar logs da guild.",
        ["HelpMergeText"] = "Cada membro exporta o CSV. O líder junta os arquivos na ferramenta da guild; as colunas são as mesmas dos outros loot loggers.",
        ["HelpFiles"] = "Onde ficam os arquivos?",
        ["HelpFilesText"] = "Cada sessão é salva sozinha, linha por linha, na pasta dos exportados. Se o programa fechar, nada se perde.",
    };

    public static readonly Dictionary<string, string> English = new()
    {
        ["NavDashboard"] = "Dashboard",
        ["NavLootLog"] = "Loot Log",
        ["NavChest"] = "Chest Check",
        ["NavCombat"] = "Combat",
        ["NavSettings"] = "Settings",
        ["NavNews"] = "What's new",
        ["NavHelp"] = "Help",
        ["NavAbout"] = "About",

        ["InGame"] = "In game",
        ["OutOfGame"] = "Out of game",
        ["ServerAmericas"] = "Americas",
        ["ServerEurope"] = "Europe",
        ["ServerAsia"] = "Asia",
        ["ServerUnknown"] = "Unknown server",
        ["WaitingGame"] = "Waiting for the game… log in or change map",
        ["PartyCount"] = "Party: {0}",
        ["Solo"] = "No party",

        ["ExportCsv"] = "Export CSV",
        ["NewSession"] = "New session",
        ["TileItems"] = "ITEMS CAPTURED",
        ["TileLastHour"] = "LAST HOUR",
        ["TileActive"] = "ACTIVE TIME",
        ["TileValue"] = "ESTIMATED VALUE",
        ["RecentEvents"] = "RECENT EVENTS",
        ["NoEventsYet"] = "Nothing captured yet. Loot a bag in game and it shows up here.",
        ["FeedLoot"] = "{0} looted {1}{2} from {3}",
        ["FeedKill"] = "{0} ({1}) was killed by {2} ({3})",
        ["FeedSessionStarted"] = "Session started",
        ["FeedCaptureStarted"] = "Capture started",
        ["FeedCaptureStopped"] = "Capture stopped",
        ["FeedGameDetected"] = "Game traffic detected",
        ["FeedMapChanged"] = "Map: {0}",
        ["NpcapMissingTitle"] = "Npcap is missing",
        ["NpcapMissingText"] = "LootLogger uses Npcap (free) to read the game traffic. Install it and open the program again.",
        ["NpcapDownload"] = "Download Npcap",
        ["CaptureError"] = "Could not start the capture: {0}",
        ["RecordError"] = "Capture is running, but recording failed: {0}",
        ["Exported"] = "Exported: {0}",
        ["NothingToExport"] = "Nothing to export yet.",
        ["ConfirmNewSession"] = "Start a new session? The current one is already saved in {0}.",
        ["Yes"] = "Yes",
        ["No"] = "No",
        ["Mob"] = "monster",
        ["Million"] = "M",
        ["Thousand"] = "k",

        ["SearchHint"] = "Search player or item…",
        ["AllGuilds"] = "All guilds",
        ["ColTime"] = "TIME",
        ["ColLootedBy"] = "LOOTED BY",
        ["ColItem"] = "ITEM",
        ["ColQty"] = "QTY",
        ["ColLootedFrom"] = "FROM",
        ["ColMap"] = "MAP",
        ["ColValue"] = "VALUE",
        ["LootSummary"] = "{0} items · {1} players",

        ["PasteChestLog"] = "Paste chest log",
        ["OpenFile"] = "Open file…",
        ["ClearChest"] = "Clear",
        ["ChestHowTo"] = "In game, open the guild chest, go to Log, click Copy and then Paste chest log here. You can paste several tabs.",
        ["TileSessionLoot"] = "SESSION LOOT",
        ["TileDeposited"] = "DEPOSITED",
        ["TileMissing"] = "MISSING",
        ["TileMissingValue"] = "MISSING VALUE",
        ["ByPlayer"] = "BY PLAYER",
        ["SortedByMissing"] = "sorted by missing",
        ["ColPlayer"] = "PLAYER",
        ["ColLooted"] = "LOOTED",
        ["ColDeposited"] = "DEPOSITED",
        ["ColMissing"] = "MISSING",
        ["ColMissingItems"] = "MISSING ITEMS",
        ["ColStatus"] = "STATUS",
        ["StatusOk"] = "Ok",
        ["StatusPartial"] = "Partial",
        ["StatusPending"] = "Pending",
        ["ChestLinesRead"] = "{0} chest lines read",
        ["ChestNothingRead"] = "No chest log lines found in the copied text.",

        ["OnlyMyGuild"] = "Only my guild",
        ["TileKills"] = "KILLS",
        ["TileDeaths"] = "DEATHS",
        ["ColDied"] = "DIED",
        ["ColKiller"] = "KILLER",
        ["ColLost"] = "LOST",
        ["NothingLost"] = "—",

        ["PartyMode"] = "Party mode",
        ["PartyModeHelp"] = "Only records loot from people in your party.",
        ["Language"] = "Language",
        ["LanguageHelp"] = "Changes the program texts. Item names follow the chosen language.",
        ["Adapter"] = "Network adapter",
        ["AdapterHelp"] = "Leave it on Automatic: it works with ExitLag and needs no Npcap. Picking an adapter uses Npcap.",
        ["AdapterAuto"] = "Automatic (all)",
        ["ExportFolder"] = "Export folder",
        ["Change"] = "Change…",
        ["OpenFolder"] = "Open folder",
        ["ItemList"] = "Item list",
        ["ItemListHelp"] = "{0} items loaded. Updates by itself when the game adds items.",
        ["UpdateNow"] = "Update now",
        ["ItemListUpdated"] = "Item list updated.",
        ["ItemListFailed"] = "Could not update the item list right now.",
        ["Advanced"] = "Advanced",
        ["RecordCapture"] = "Record capture for diagnostics",
        ["RecordCaptureHelp"] = "Saves the game traffic to a .pcap file in the data folder. Only use it when asked to help find a bug.",
        ["ReplayRecording"] = "Open recording…",
        ["OpenDataFolder"] = "Data folder",

        ["AboutMadeBy"] = "Made by Vitor. It only reads the game traffic; it does not change the client or play for you.",
        ["AboutFanProject"] = "Fan project, not affiliated with Sandbox Interactive GmbH. Albion Online is a trademark of Sandbox Interactive.",
        ["AboutLicense"] = "Open source under the GPL-3.0 license.",
        ["AboutCredits"] = "Uses parts of AlbionOnline-StatisticsAnalysis (Triky313, GPL-3.0), SharpPcap, PacketDotNet, CommunityToolkit.Mvvm, the Geist font and the ao-bin-dumps item list.",
        ["Version"] = "version {0}",

        ["NewsBody"] = "First version: live capture, Loot Log, CSV export in the format guilds already use, Chest Check, Combat, Party mode and Portuguese/English.",
        ["HelpNoCapture"] = "Nothing is captured?",
        ["HelpNoCaptureText"] = "Check that the network adapter is on Automatic and that Windows asked for administrator permission when opening. Then change map in game.",
        ["HelpExitLag"] = "I use ExitLag.",
        ["HelpExitLagText"] = "It works without any setup: leave the network adapter on Automatic.",
        ["HelpPlayer"] = "It says \"player not identified\".",
        ["HelpPlayerText"] = "The game only sends your name when you log in or change map. Open LootLogger before logging in, or change map.",
        ["HelpWarning"] = "Windows warned about the program.",
        ["HelpWarningText"] = "New unsigned programs get this warning. Only download from the official GitHub releases page and click More info > Run anyway.",
        ["HelpMerge"] = "How to merge guild logs.",
        ["HelpMergeText"] = "Each member exports the CSV. The leader merges the files in the guild tool; the columns match other loot loggers.",
        ["HelpFiles"] = "Where are the files?",
        ["HelpFilesText"] = "Each session saves itself, line by line, in the export folder. If the program closes, nothing is lost.",
    };
}
