namespace LootLogger.App.Localization;

/// <summary>Interface texts. Item names come from the game data in the matching language.</summary>
internal static class Strings
{
    public static readonly Dictionary<string, string> Portuguese = new()
    {
        // Menu
        ["NavDashboard"] = "Painel",
        ["NavLootLog"] = "Loot Log",
        ["NavChest"] = "Comparar Baú",
        ["NavSettings"] = "Configurações",
        ["NavHelp"] = "Ajuda",
        ["NavAbout"] = "Sobre",

        // Status
        ["InGame"] = "No jogo",
        ["OutOfGame"] = "Fora do jogo",
        ["ServerAmericas"] = "Américas",
        ["ServerEurope"] = "Europa",
        ["ServerAsia"] = "Ásia",
        ["ServerUnknown"] = "Servidor desconhecido",
        ["WaitingGame"] = "Esperando o jogo… entre no personagem ou troque de mapa",
        ["PartyCount"] = "Party: {0}",
        ["Solo"] = "Sem party",

        // Dashboard
        ["ExportCsv"] = "Exportar CSV",
        ["NewSession"] = "Nova sessão",
        ["TileItems"] = "ITENS CAPTURADOS",
        ["TileLastHour"] = "ÚLTIMA HORA",
        ["TileActive"] = "TEMPO ATIVO",
        ["TileValue"] = "VALOR ESTIMADO",
        ["RecentEvents"] = "EVENTOS RECENTES",
        ["NoEventsYet"] = "Nada capturado ainda. Pegue uma bag no jogo e ela aparece aqui.",
        ["FeedLoot"] = "{0} pegou {1}{2} de {3}",
        ["FeedKill"] = "{0} ({1}) morreu para {2} ({3})",
        ["FeedSessionStarted"] = "Sessão iniciada",
        ["FeedCaptureStarted"] = "Captura iniciada",
        ["FeedCaptureStopped"] = "Captura parada",
        ["FeedGameDetected"] = "Tráfego do jogo detectado",
        ["FeedMapChanged"] = "Mapa: {0}",
        ["CaptureError"] = "Não deu para iniciar a captura: {0}",
        ["Updating"] = "Versão nova baixada. Reiniciando o LootLogger…",
        ["RecordError"] = "A captura continua, mas não deu para gravar: {0}",
        ["Exported"] = "Exportado: {0}",
        ["NothingToExport"] = "Ainda não há nada para exportar.",
        ["Yes"] = "Sim",
        ["No"] = "Não",
        ["Mob"] = "monstro",
        ["Chest"] = "baú",
        ["Million"] = "mi",
        ["Thousand"] = "mil",

        // Loot log
        ["SearchHint"] = "Buscar jogador ou item…",
        ["LootSummary"] = "{0} itens · {1} no total",
        ["LootSummaryMine"] = "seu loot: {0} itens, {1}",
        ["LootedFromLine"] = "de {0}",
        ["NoPrice"] = "sem preço",
        ["FilterAll"] = "Todos",
        ["FilterMine"] = "Meu loot",
        ["FilterMyGuild"] = "Minha guild",
        ["TabList"] = "Lista",
        ["TabStats"] = "Estatísticas",
        ["StatsItems"] = "ITENS",
        ["StatsValue"] = "VALOR TOTAL",
        ["StatsPlayers"] = "JOGADORES",
        ["StatsMine"] = "SEU LOOT",
        ["TopByItems"] = "QUEM PEGOU MAIS ITENS",
        ["TopByValue"] = "QUEM PEGOU MAIS VALOR",
        ["TopItems"] = "ITENS MAIS CAROS",
        ["StatsEmpty"] = "Ainda não tem loot nesta sessão.",

        // Chest
        ["PasteChestLog"] = "Colar log do baú",
        ["OpenFile"] = "Abrir arquivo…",
        ["ClearChest"] = "Limpar",
        ["ChestHowTo"] = "No jogo, abra o baú da guild, vá em Log, clique em Copiar e depois em Colar log do baú aqui. Pode colar várias abas.",
        ["TileSessionLoot"] = "LOOT DA SESSÃO",
        ["TileDeposited"] = "DEPOSITADO",
        ["TileMissing"] = "FALTANDO",
        ["TileMissingValue"] = "VALOR FALTANDO",
        ["ByPlayer"] = "POR JOGADOR",
        ["SortedByMissing"] = "ordenado pelo que falta",
        ["ColPlayer"] = "JOGADOR",
        ["ColLooted"] = "PEGOU",
        ["ColDeposited"] = "DEPOSITOU",
        ["ColMissing"] = "FALTA",
        ["ColMissingItems"] = "ITENS QUE FALTAM",
        ["ColStatus"] = "SITUAÇÃO",
        ["StatusOk"] = "Ok",
        ["StatusPartial"] = "Parcial",
        ["StatusPending"] = "Pendente",
        ["ChestLinesRead"] = "{0} linhas do baú lidas",
        ["ChestNothingRead"] = "Não achei linhas de log do baú no texto copiado.",
        ["LootFiles"] = "ARQUIVOS DE LOOT",
        ["StartupError"] = "O LootLogger deu erro ao abrir. Feche e abra de novo daqui a pouco; se continuar, mande o arquivo erros.log da pasta %AppData%\\LootLogger.",
        ["LiveSession"] = "Sessão atual",
        ["LiveDetail"] = "ao vivo · {0} itens",
        ["SourceDetail"] = "{0} itens · {1}",
        ["PickFile"] = "Selecionar arquivo",
        ["RemoveFromList"] = "Tirar da lista (o arquivo não é apagado)",
        ["OrDragHere"] = "ou arraste aqui",
        ["LogsMerged"] = "{0} logs juntos",
        ["DuplicatesOnce"] = "repetidos contam uma vez",
        ["NothingRead"] = "Esse arquivo não é um log de loot nem do baú.",
        ["PickChestLog"] = "Selecionar log do baú",
        ["TileLooted"] = "ITENS PEGOS",
        ["TileKept"] = "GUARDADOS",
        ["TileRate"] = "TAXA",
        ["MissingValueLine"] = "≈ {0} em prata",
        ["SearchPlayer"] = "Buscar jogador",
        ["AllGuilds"] = "Todas as guilds",
        ["OnlyDebtors"] = "Só quem deve",
        ["KindGear"] = "Equipamento",
        ["KindBag"] = "Bolsa",
        ["KindCape"] = "Capa",
        ["KindMount"] = "Montaria",
        ["KindConsumable"] = "Poção e comida",
        ["KindOther"] = "Outros",
        ["GroupMissing"] = "Faltando",
        ["GroupKept"] = "Guardou no baú",
        ["GroupPicked"] = "Pegou",
        ["GroupLost"] = "Morreu com o item",
        ["DiedLine"] = "morreu {0} UTC · morto por {1}",
        ["DiedLineNoKiller"] = "morreu {0} UTC",
        ["TileLost"] = "MORREU COM",
        ["ColPicked"] = "PEGOU",
        ["ColKept"] = "GUARDOU",
        ["ColMissingShort"] = "FALTANDO",
        ["ColDied"] = "MORREU",
        ["ItemsCount"] = "{0} itens",
        ["ChestHint"] = "Cole o log do baú para ver quem guardou. Por enquanto mostra só o que cada um pegou.",
        ["ChestEmpty"] = "Cole o log do baú para ver quem guardou o loot. No jogo: baú da guild › Log › Copiar.",
        ["ChestNoCards"] = "Ninguém aparece com esses filtros.",
        ["ChestNoLoot"] = "Nenhum loot ainda. Escolha um arquivo à esquerda ou arraste para cá.",

        // Deaths
        ["ColDied"] = "MORREU",

        // Settings
        ["PartyMode"] = "Modo Party",
        ["PartyModeHelp"] = "Registra só o loot de quem está na sua party.",
        ["Language"] = "Idioma",
        ["LanguageHelp"] = "Muda os textos do programa. Nomes de itens seguem o idioma escolhido.",
        ["ItemList"] = "Lista de itens",
        ["ItemListHelp"] = "{0} itens carregados. Atualiza sozinha quando o jogo ganha itens novos.",
        ["Advanced"] = "Avançado",
        ["RecordCapture"] = "Gravar captura para diagnóstico",
        ["RecordCaptureHelp"] = "Salva o tráfego do jogo num arquivo .pcap na pasta de dados. Use só se pedirem para ajudar a achar um erro.",
        ["OpenDataFolder"] = "Pasta de dados",

        // About
        ["AboutMadeBy"] = "Feito por Vitor. Só lê o tráfego do jogo; não altera o cliente nem joga por você.",
        ["AboutFanProject"] = "Projeto de fã, sem vínculo com a Sandbox Interactive GmbH. Albion Online é marca da Sandbox Interactive.",
        ["AboutLicense"] = "Código aberto sob a licença GPL-3.0.",
        ["AboutCredits"] = "Usa partes do AlbionOnline-StatisticsAnalysis (Triky313, GPL-3.0), SharpPcap, PacketDotNet, CommunityToolkit.Mvvm, a fonte Geist e a lista de itens do ao-bin-dumps.",
        ["Version"] = "versão {0}",

        // Help
        ["HelpNoCapture"] = "Não captura nada?",
        ["HelpNoCaptureText"] = "Confira se o Windows pediu permissão de administrador ao abrir o LootLogger e se você clicou em Sim. Depois troque de mapa no jogo.",
        ["HelpExitLag"] = "Uso ExitLag.",
        ["HelpExitLagText"] = "Funciona sem configurar nada e não precisa instalar o Npcap.",
        ["HelpPlayer"] = "Aparece \"jogador não identificado\".",
        ["HelpPlayerText"] = "O jogo só manda o seu nome ao entrar no personagem ou trocar de mapa. Abra o LootLogger antes de entrar no jogo, ou troque de mapa.",
        ["HelpWarning"] = "O Windows avisou sobre o programa.",
        ["HelpWarningText"] = "Programas novos e sem assinatura recebem esse aviso. Baixe só da página oficial de releases no GitHub e clique em Mais informações > Executar assim mesmo.",
        ["HelpMerge"] = "Como juntar os logs da guild?",
        ["HelpMergeText"] = "Cada membro clica em Exportar CSV e manda o arquivo. Na aba Comparar Baú, arraste todos os arquivos da luta: o item visto por mais de uma pessoa conta uma vez só. Depois cole o log do baú para ver quem guardou.",
        ["HelpFiles"] = "Onde ficam os arquivos?",
        ["HelpFilesText"] = "Clique em Exportar CSV (no Painel ou no Loot Log) e escolha onde salvar. Enquanto você joga, o LootLogger também guarda uma cópia sozinho, então nada se perde se ele fechar.",
    };

    public static readonly Dictionary<string, string> English = new()
    {
        ["NavDashboard"] = "Dashboard",
        ["NavLootLog"] = "Loot Log",
        ["NavChest"] = "Chest Check",
        ["NavSettings"] = "Settings",
        ["NavHelp"] = "Help",
        ["NavAbout"] = "About",

        ["InGame"] = "In game",
        ["OutOfGame"] = "Out of game",
        ["ServerAmericas"] = "Americas",
        ["ServerEurope"] = "Europe",
        ["ServerAsia"] = "Asia",
        ["ServerUnknown"] = "Unknown server",
        ["WaitingGame"] = "Waiting for the game… log in or change map",
        ["PartyCount"] = "Party: {0}",
        ["Solo"] = "No party",

        ["ExportCsv"] = "Export CSV",
        ["NewSession"] = "New session",
        ["TileItems"] = "ITEMS CAPTURED",
        ["TileLastHour"] = "LAST HOUR",
        ["TileActive"] = "ACTIVE TIME",
        ["TileValue"] = "ESTIMATED VALUE",
        ["RecentEvents"] = "RECENT EVENTS",
        ["NoEventsYet"] = "Nothing captured yet. Loot a bag in game and it shows up here.",
        ["FeedLoot"] = "{0} looted {1}{2} from {3}",
        ["FeedKill"] = "{0} ({1}) was killed by {2} ({3})",
        ["FeedSessionStarted"] = "Session started",
        ["FeedCaptureStarted"] = "Capture started",
        ["FeedCaptureStopped"] = "Capture stopped",
        ["FeedGameDetected"] = "Game traffic detected",
        ["FeedMapChanged"] = "Map: {0}",
        ["CaptureError"] = "Could not start the capture: {0}",
        ["Updating"] = "New version downloaded. Restarting LootLogger…",
        ["RecordError"] = "Capture is running, but recording failed: {0}",
        ["Exported"] = "Exported: {0}",
        ["NothingToExport"] = "Nothing to export yet.",
        ["Yes"] = "Yes",
        ["No"] = "No",
        ["Mob"] = "monster",
        ["Chest"] = "chest",
        ["Million"] = "M",
        ["Thousand"] = "k",

        ["SearchHint"] = "Search player or item…",
        ["LootSummary"] = "{0} items · {1} in total",
        ["LootSummaryMine"] = "your loot: {0} items, {1}",
        ["LootedFromLine"] = "from {0}",
        ["NoPrice"] = "no price",
        ["FilterAll"] = "All",
        ["FilterMine"] = "My loot",
        ["FilterMyGuild"] = "My guild",
        ["TabList"] = "List",
        ["TabStats"] = "Statistics",
        ["StatsItems"] = "ITEMS",
        ["StatsValue"] = "TOTAL VALUE",
        ["StatsPlayers"] = "PLAYERS",
        ["StatsMine"] = "YOUR LOOT",
        ["TopByItems"] = "MOST ITEMS LOOTED",
        ["TopByValue"] = "MOST VALUE LOOTED",
        ["TopItems"] = "MOST EXPENSIVE ITEMS",
        ["StatsEmpty"] = "No loot in this session yet.",

        ["PasteChestLog"] = "Paste chest log",
        ["OpenFile"] = "Open file…",
        ["ClearChest"] = "Clear",
        ["ChestHowTo"] = "In game, open the guild chest, go to Log, click Copy and then Paste chest log here. You can paste several tabs.",
        ["TileSessionLoot"] = "SESSION LOOT",
        ["TileDeposited"] = "DEPOSITED",
        ["TileMissing"] = "MISSING",
        ["TileMissingValue"] = "MISSING VALUE",
        ["ByPlayer"] = "BY PLAYER",
        ["SortedByMissing"] = "sorted by missing",
        ["ColPlayer"] = "PLAYER",
        ["ColLooted"] = "LOOTED",
        ["ColDeposited"] = "DEPOSITED",
        ["ColMissing"] = "MISSING",
        ["ColMissingItems"] = "MISSING ITEMS",
        ["ColStatus"] = "STATUS",
        ["StatusOk"] = "Ok",
        ["StatusPartial"] = "Partial",
        ["StatusPending"] = "Pending",
        ["ChestLinesRead"] = "{0} chest lines read",
        ["ChestNothingRead"] = "No chest log lines found in the copied text.",
        ["LootFiles"] = "LOOT FILES",
        ["StartupError"] = "LootLogger failed to open. Close it and try again in a while; if it keeps happening, send the erros.log file from %AppData%\\LootLogger.",
        ["LiveSession"] = "Current session",
        ["LiveDetail"] = "live · {0} items",
        ["SourceDetail"] = "{0} items · {1}",
        ["PickFile"] = "Select file",
        ["RemoveFromList"] = "Remove from the list (the file is not deleted)",
        ["OrDragHere"] = "or drag it here",
        ["LogsMerged"] = "{0} logs merged",
        ["DuplicatesOnce"] = "duplicates count once",
        ["NothingRead"] = "That file is neither a loot log nor a chest log.",
        ["PickChestLog"] = "Select chest log",
        ["TileLooted"] = "ITEMS LOOTED",
        ["TileKept"] = "DEPOSITED",
        ["TileRate"] = "RATE",
        ["MissingValueLine"] = "≈ {0} silver",
        ["SearchPlayer"] = "Search player",
        ["AllGuilds"] = "All guilds",
        ["OnlyDebtors"] = "Only who owes",
        ["KindGear"] = "Gear",
        ["KindBag"] = "Bag",
        ["KindCape"] = "Cape",
        ["KindMount"] = "Mount",
        ["KindConsumable"] = "Potions and food",
        ["KindOther"] = "Other",
        ["GroupMissing"] = "Missing",
        ["GroupKept"] = "Deposited",
        ["GroupPicked"] = "Looted",
        ["GroupLost"] = "Died carrying",
        ["DiedLine"] = "died {0} UTC · killed by {1}",
        ["DiedLineNoKiller"] = "died {0} UTC",
        ["TileLost"] = "DIED CARRYING",
        ["ColPicked"] = "LOOTED",
        ["ColKept"] = "DEPOSITED",
        ["ColMissingShort"] = "MISSING",
        ["ColDied"] = "DIED",
        ["ItemsCount"] = "{0} items",
        ["ChestHint"] = "Paste the chest log to see who deposited. For now it only shows what each player looted.",
        ["ChestEmpty"] = "Paste the chest log to see who deposited the loot. In game: guild chest › Log › Copy.",
        ["ChestNoCards"] = "Nobody matches these filters.",
        ["ChestNoLoot"] = "No loot yet. Pick a file on the left or drag one here.",

        ["ColDied"] = "DIED",

        ["PartyMode"] = "Party mode",
        ["PartyModeHelp"] = "Only records loot from people in your party.",
        ["Language"] = "Language",
        ["LanguageHelp"] = "Changes the program texts. Item names follow the chosen language.",
        ["ItemList"] = "Item list",
        ["ItemListHelp"] = "{0} items loaded. Updates by itself when the game adds items.",
        ["Advanced"] = "Advanced",
        ["RecordCapture"] = "Record capture for diagnostics",
        ["RecordCaptureHelp"] = "Saves the game traffic to a .pcap file in the data folder. Only use it when asked to help find a bug.",
        ["OpenDataFolder"] = "Data folder",

        ["AboutMadeBy"] = "Made by Vitor. It only reads the game traffic; it does not change the client or play for you.",
        ["AboutFanProject"] = "Fan project, not affiliated with Sandbox Interactive GmbH. Albion Online is a trademark of Sandbox Interactive.",
        ["AboutLicense"] = "Open source under the GPL-3.0 license.",
        ["AboutCredits"] = "Uses parts of AlbionOnline-StatisticsAnalysis (Triky313, GPL-3.0), SharpPcap, PacketDotNet, CommunityToolkit.Mvvm, the Geist font and the ao-bin-dumps item list.",
        ["Version"] = "version {0}",

        ["HelpNoCapture"] = "Nothing is captured?",
        ["HelpNoCaptureText"] = "Check that Windows asked for administrator permission when opening LootLogger and that you clicked Yes. Then change map in game.",
        ["HelpExitLag"] = "I use ExitLag.",
        ["HelpExitLagText"] = "It works without any setup and does not need Npcap.",
        ["HelpPlayer"] = "It says \"player not identified\".",
        ["HelpPlayerText"] = "The game only sends your name when you log in or change map. Open LootLogger before logging in, or change map.",
        ["HelpWarning"] = "Windows warned about the program.",
        ["HelpWarningText"] = "New unsigned programs get this warning. Only download from the official GitHub releases page and click More info > Run anyway.",
        ["HelpMerge"] = "How to merge the guild's logs?",
        ["HelpMergeText"] = "Each member clicks Export CSV and sends the file. In the Chest Check tab, drag in every file from the fight: an item seen by more than one person counts once. Then paste the chest log to see who deposited.",
        ["HelpFiles"] = "Where are the files?",
        ["HelpFilesText"] = "Click Export CSV (on the Dashboard or Loot Log) and choose where to save. While you play, LootLogger also keeps a copy on its own, so nothing is lost if it closes.",
    };
}
